name: Continuous integration

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install rust
      uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt, rust-src
        rust-version: nightly
    - name: Compile detextify (x86_64-uwp-windows-msvc)
      run: cargo build --package detexify-c --release -Z build-std=std,panic_abort --target x86_64-uwp-windows-msvc
      working-directory: ./submodules/detexify-rust
    - name: Compile detextify (i686-uwp-windows-msvc)
      run: cargo build --package detexify-c --release -Z build-std=std,panic_abort --target i686-uwp-windows-msvc
      working-directory: ./submodules/detexify-rust
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build solution
      run: MSBuild TeX-Match/TeX-Match.sln /restore /t:Build /p:Configuration=Release /p:Platform=x64 /p:AppxPackageSigningEnabled=false
      working-directory: ./TeX-Match-Windows

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install rust
      uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt
        rust-version: 1.46.0
    - name: Cache cargo
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Dependencies
      run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev
    - name: Check
      run: cargo check
      working-directory: ./TeX-Match-Linux
    - name: Test
      run: cargo test -- --nocapture
      working-directory: ./TeX-Match-Linux
    - name: Fmt
      run: cargo fmt --all -- --check
      working-directory: ./TeX-Match-Linux
    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: ./TeX-Match-Linux

  snap:
    name: snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: snapcore/action-build@v1

  flatpak:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Dependency (Python TOML)
        run: sudo dnf install -y python3-toml
      - name: Generate sources
        run: bash flatpak/gen-sources.sh
        working-directory: ./TeX-Match-Linux
      - uses: bilelmoussaoui/flatpak-github-actions@v3
        with:
          manifest-path: "TeX-Match-Linux/flatpak/fyi.zoey.TeX-Match.json"

  metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt-get install -y appstream-util desktop-file-utils
      - name: Validate data/fyi.zoey.TeX-Match.metainfo.xml
        run: appstream-util validate-relax data/fyi.zoey.TeX-Match.metainfo.xml
        working-directory: ./TeX-Match-Linux
      - name: Validate data/fyi.zoey.TeX-Match.desktop
        run: desktop-file-validate data/fyi.zoey.TeX-Match.desktop
        working-directory: ./TeX-Match-Linux